# Generated by Django 4.0.2 on 2022-02-17 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'Female'), ('0', 'Male'), ('2', 'Other')], default='1', max_length=1)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Designation', models.BooleanField()),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvsmodel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-added_on',),
            },
        ),
    ]
