# Generated by Django 4.0.2 on 2022-02-17 06:26

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvmodel',
            options={'ordering': ('-added_on',), 'verbose_name_plural': 'CSVs'},
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='Designation',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='date_of_birth',
            field=models.DateField(validators=[webapp.validators.validate_DOB]),
        ),
    ]
