# Generated by Django 4.0.2 on 2022-02-17 06:50

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_csvmodel_options_alter_csvmodel_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='date_of_birth',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', validators=[webapp.validators.validate_DOB]),
        ),
    ]
