# Generated by Django 4.0.2 on 2022-02-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_designation_csvmodel_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='designation',
            field=models.CharField(max_length=80),
        ),
    ]
