# Generated by Django 4.0.2 on 2022-02-17 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0005_alter_csvmodel_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvsmodel', related_query_name='has_uploaded', to=settings.AUTH_USER_MODEL),
        ),
    ]
